[package]
name = "vdsportal"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jni = { version = "=0.22.4", default-features = false }
rusb = "=0.9.4"
zbus = { version = "=5.19.0", default-features = false, features = ["tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "time", "sync", "macros"] }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }

[profile.release]
lto = "thin"
